config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
# 後でskip: registrationsを入れる
devise_for :admin, skip: [:passwords] ,controllers: {
  registrations: "admin/registrations",
  sessions: "admin/sessions"
}

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about', as: 'about'
    get '/customers/my_page' => 'customers#show', as: 'my_page'
    get '/customers/infomation/edit' => 'customers#edit', as: 'edit_infomation'
    patch '/customers/infomation' => 'customers#update', as: 'infomation'
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'

    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get '/orders/purchase_completed' => 'orders#purchase_completed'
    resources :orders, only: [:new, :create, :index, :show]
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'

  end

  namespace :admin do
  get 'home' => 'homes#top'
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, only: [:index, :new, :show, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def total_price
    item.add_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def status
    if is_active == true
      "販売中"
    else
      "販売停止中"
    end
  end

  def add_tax_price
    (self.price*1.10).round
  end

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 1, transfer: 2 }
  enum status: { waiting_for_payment: 1, payment_confirmation: 2, in_production: 3, preparing_for_ship: 4, shipped: 5 }

  def postage
    800
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { cannot_be_produced: 1, waiting_for_production: 2, in_production: 3, completion_of_production: 4 }


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 2) if @order.status == "payment_confirmation"
    end
    redirect_to admin_order_path(@order)
  end

  private
    def order_params
      params.require(:order).permit(:status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_in_path_for(resource)
  #   case resource
  #   when Customer
  #   items_path
  #   when Admin
  #   admin_homes_path
  #   end
  # end

  # def after_sign_out_path_for(resource)
  #   case resource
  #   when Customer
  #   root_path
  #   when Admin
  #   new_admin_session_path
  #   end
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana,
    :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custmoers_helper.rb
module CustmoersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h4 style="background-color: silver;">注文履歴詳細</h4>
  </div>

<p>購入者
  　<%= link_to (@order.customer.last_name + " " + @order.customer.first_name), admin_customer_path(@order.customer) %>
</p>

<p>注文日 <%= @order.created_at.to_s(:datetime_jp) %></p>

<p>配送先 〒<%= @order.postal_code + @order.address + @order.name %></p>

<p>支払方法 <%= @order.payment_method_i18n %></p>

<%= form_with model: @order, url: admin_order_path, method: :patch, local:true do |f| %>
<p>注文ステータス
　　<%= f.select :status, Order.statuses_i18n.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
　  <%= f.submit '更新', class: "btn btn-success" %>
</p>

<% end %>

<table>
  <thead>
      <th class="border col-2", style="background-color: silver;">商品名</th>
      <th class="border col-2", style="background-color: silver;">単価（税込）</th>
      <th class="border col-2", style="background-color: silver;">数量</th>
      <th class="border col-2", style="background-color: silver;">小計</th>
      <th class="border col-3", style="background-color: silver;">製作ステータス</th>
  </thead>
  <tbody>
<% @order.order_details.each do |order_detail| %>
  <tr>
    <td class="border-bottom col-3 pb-3">
      <%= order_detail.item.name %>
    </td>
    <td class="border-bottom col-3 pb-3"><%= order_detail.item.price.to_s(:delimited) %></td>
    <td class="border-bottom col-3 pb-3"><%= order_detail.amount %></td>
    <td class="border-bottom col-3 pb-3">
      <%= (order_detail.item.add_tax_price*order_detail.amount).to_s(:delimited) %></td>
      <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, local:true do |f| %>
    <td class="border-bottom col-3 pb-3">
      <%= f.select :making_status, OrderDetail.making_statuses_i18n.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
      <%= f.submit '更新', class: "btn btn-success" %>
    </td>
    <% end %>
  </tr>
  <% end %>


  <h5>商品合計 <%= @order.billing.to_s(:delimited) %>円</h5>
  <h5>送料 <%= @order.postage %>円</h5>
  <h5>請求金額合計 <%= (@order.billing + @order.postage).to_s(:delimited) %>円</h5>

</div>