config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
# 後でskip: registrationsを入れる
devise_for :admin, skip: [:passwords] ,controllers: {
  registrations: "admin/registrations",
  sessions: "admin/sessions"
}

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about', as: 'about'
    get '/customers/my_page' => 'customers#show', as: 'my_page'
    get '/customers/infomation/edit' => 'customers#edit', as: 'edit_infomation'
    patch '/customers/infomation' => 'customers#update', as: 'infomation'
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'

    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get '/orders/purchase_completed' => 'orders#purchase_completed'
    resources :orders, only: [:new, :create, :index, :show]
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'

  end

  namespace :admin do
  get 'home' => 'homes#top'
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, only: [:index, :new, :show, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def total_price
    item.add_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def status
    if is_active == true
      "販売中"
    else
      "販売停止中"
    end
  end

  def add_tax_price
    (self.price*1.10).round
  end

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 1, transfer: 2 }
  enum status: { waiting_for_payment: 1, payment_confirmation: 2, in_production: 3, preparing_for_ship: 4, shipped: 5 }

  def postage
    800
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { cannot_be_produced: 1, waiting_for_production: 2, in_production: 3, completion_of_production: 4 }


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @item = Item.new
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private
  def item_params
    params.require(:item).permit(:image, :genre_id, :name, :introduction, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_in_path_for(resource)
  #   case resource
  #   when Customer
  #   items_path
  #   when Admin
  #   admin_homes_path
  #   end
  # end

  # def after_sign_out_path_for(resource)
  #   case resource
  #   when Customer
  #   root_path
  #   when Admin
  #   new_admin_session_path
  #   end
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana,
    :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custmoers_helper.rb
module CustmoersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <h4 style="background-color: silver;">注文履歴一覧</h4>
  </div>

<table>
  <thead>
      <th class="border col-3", style="background-color: silver;">購入日時</th>
      <th class="border col-3", style="background-color: silver;">購入者</th>
      <th class="border col-3", style="background-color: silver;">注文個数</th>
      <th class="border col-3", style="background-color: silver;">注文ステータス</th>
　</thead>
  <tbody>
<% @orders.each do |order| %>
  <tr>
    <td class="border-bottom col-3 pb-3"><%= link_to order.created_at.to_s(:datetime_jp), admin_order_path(order.id) %></td>
    <td class="border-bottom col-3 pb-3"><%= order.customer.last_name %><%= order.customer.first_name %></td>
    <td class="border-bottom col-3 pb-3"><%= order.order_details.sum(:amount) %></td>
    <td class="border-bottom col-3 pb-3"><%= order.status_i18n %></td>
  </tr>
  <% end %>
  </tbody>
</table>
 <div class="row">
   <div class="col-4"></div>
   <div class="col-4"><%= paginate @orders %></div>
 </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <h4 style="background-color: silver;">商品編集</h4>
  </div>
    <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-2">商品画像</div>
    <div class="col-4"><%= f.file_field :image %></div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-2">商品名</div>
    <div class="col-4"><%= f.text_field :name, include_blank: "商品名" %></div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-2">商品説明</div>
    <div class="col-4"><%= f.text_area :introduction, include_blank: "ここに説明文を記述します" %></div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-2">ジャンル</div>
    <div class="col-4"><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %></div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-2">税抜価格</div>
    <div class="col-4"><%= f.text_field :price, include_blank: "1000" %>円</div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-3">販売ステータス</div>
    <div class="col-2">
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, "販売中" %>
    </div>
    <div class="col-3">
      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active, "販売停止中" %>
    </div>
  </div>

  <div class="row">
    <div class="col-4"></div>
    <div class="col-4"><%= f.submit '変更を保存', class: "btn btn-success" %></div>
    <div class="col-4"></div>
  </div>
    <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="col-4",style="background-color: silver;">商品一覧</h4>
    <div class="col-2"></div>
    <div class="col-2"></div>
    <div class="col-2"></div>
    <div class="col-2"><%= link_to "＋", new_admin_item_path(@item.id), class: "btn btn-info" %></div>
  </div>

  <div class="row">
  <table>
    <thead>
        <th class="border col-2", style="background-color: silver;">商品ID</th>
        <th class="border col-2", style="background-color: silver;">商品名</th>
        <th class="border col-2", style="background-color: silver;">税抜価格</th>
        <th class="border col-2", style="background-color: silver;">ジャンル</th>
        <th class="border col-2", style="background-color: silver;">ステータス</th>
    </thead>
    <tbody>
    <% @items.each do |item| %>
      <tr>
        <td class="border col-2"><%= item.id %></td>
        <td class="border col-2"><%= link_to item.name, admin_item_path(item.id) %></td>
        <td class="border col-2"><%= item.price.to_s(:delimited) %></td>
        <td class="border col-2"><%= item.genre.name %></td>
        <td class="border col-2">
          <% if item.is_active == true %>
          <span class="text-success">有効</span>
          <% else %>
          <span class="text-dark">退会</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <h4 style="background-color: silver;">商品新規登録</h4>
  </div>

    <%= form_with model: @item, url:  admin_items_path, method: :post, local:true do |f| %>
  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-2">商品画像</div>
    <div class="col-4"><%= f.file_field :image %></div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-2">商品名</div>
    <div class="col-4"><%= f.text_field :name, include_blank: "商品名" %></div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-2">商品説明</div>
    <div class="col-4"><%= f.text_area :introduction, include_blank: "ここに説明文を記述します" %></div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-2">ジャンル</div>
    <div class="col-4"><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %></div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-2">税抜価格</div>
    <div class="col-4"><%= f.text_field :price, include_blank: "1000" %>円</div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-3">販売ステータス</div>
    <div class="col-2">
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, "販売中" %>
    </div>
    <div class="col-3">
      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active, "販売停止中" %>
    </div>
  </div>

  <div class="row">
    <div class="col-4"></div>
    <div class="col-4"><%= f.submit '新規登録', class: "btn btn-success" %></div>
    <div class="col-4"></div>
  </div>

    <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row pb-5">
    <h4 style="background-color: silver;">商品詳細</h4>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-4"><%= image_tag @item.get_image, :size => '400x300' %></div>
    <div class="col-4"></div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-3">商品名</div>
    <div class="col-3"><%= @item.name %></div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-3">商品説明</div>
    <div class="col-3"><%= @item.introduction %></div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-3">ジャンル</div>
    <div class="col-3"><%= @item.genre.name %></div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-3">税込価格（税抜価格）</div>
    <div class="col-3"><%= @item.add_tax_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>)円</div>
  </div>

  <div class="row pb-3">
    <div class="col-2"></div>
    <div class="col-3">販売ステータス</div>
    <div class="col-3"><%= @item.status %></div>
  </div>

  <div class="row pb-3">
    <div class="col-5"></div>
    <div class="col-3"><%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %></div>
    <div class="col-3"></div>
  </div>
</div>