config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
# 後でskip: registrationsを入れる
devise_for :admin, skip: [:passwords] ,controllers: {
  registrations: "admin/registrations",
  sessions: "admin/sessions"
}

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about', as: 'about'
    get '/customers/my_page' => 'customers#show', as: 'my_page'
    get '/customers/infomation/edit' => 'customers#edit', as: 'edit_infomation'
    patch '/customers/infomation' => 'customers#update', as: 'infomation'
    get '/customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw', as: 'withdraw'

    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get '/orders/purchase_completed' => 'orders#purchase_completed'
    resources :orders, only: [:new, :create, :index, :show]
    post '/orders/confirm' => 'orders#confirm', as: 'confirm'

  end

  namespace :admin do
  get 'home' => 'homes#top'
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, only: [:index, :new, :show, :create, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def total_price
    item.add_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def status
    if is_active == true
      "販売中"
    else
      "販売停止中"
    end
  end

  def add_tax_price
    (self.price*1.10).round
  end

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 1, transfer: 2 }
  enum status: { waiting_for_payment: 1, payment_confirmation: 2, in_production: 3, preparing_for_ship: 4, shipped: 5 }

  def postage
    800
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { cannot_be_produced: 1, waiting_for_production: 2, in_production: 3, completion_of_production: 4 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def after_sign_in_path_for(resource)
  #   case resource
  #   when Customer
  #   items_path
  #   when Admin
  #   admin_homes_path
  #   end
  # end

  # def after_sign_out_path_for(resource)
  #   case resource
  #   when Customer
  #   root_path
  #   when Admin
  #   new_admin_session_path
  #   end
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana,
    :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custmoers_helper.rb
module CustmoersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container pt-5 pb-3">
        <div class="row">
      <% if customer_signed_in? %>
          <h5 class="col-2">LOGO</h5>
          <h6 class="col-2">ようこそ,<%= current_customer.last_name %>さん!</h6>
          <div class="col-2">
            <%= link_to "マイページ", my_page_path, class: "border" %>
          </div>
          <div class="col-2">
            <%= link_to "商品一覧", items_path, class: "border" %>
          </div>
          <div class="col-2">
            <%= link_to "カート", cart_items_path, class: "border" %>
          </div>
          <div class="col-2">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "border" %>
          </div>
        </div>
      </div>

      <div class="container pt-5 pb-3">
        <div class="row">
      <% elsif admin_signed_in? %>
          <h5 class="col-2">LOGO</h5>
          <div class="col-2">
            <%= link_to "商品一覧", admin_items_path, class: "border" %>
          </div>
          <div class="col-2">
            <%= link_to "会員一覧", admin_customers_path, class: "border" %>
          </div>
          <div class="col-2">
            <%= link_to "注文履歴一覧", admin_home_path, class: "border" %>
          </div>
          <div class="col-2">
            <%= link_to "ジャンル一覧", admin_genres_path, class: "border" %>
          </div>
          <div class="col-2">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "border" %>
          </div>
        </div>
      </div>

      <div class="container pt-5 pb-3">
        <div class="row">
          <% else %>
          <h5 class="col-2">LOGO</h5>
          <div class="col-2">
            <%= link_to "About", about_path, class: "border" %>
          </div>
          <div class="col-2">
            <%= link_to "商品一覧", items_path, class: "border" %>
          </div>
          <div class="col-2">
            <%= link_to "新規登録", new_customer_registration_path, class: "border" %>
          </div>
          <div class="col-2">
            <%= link_to "ログイン", new_customer_session_path, class: "border" %>
          </div>
          <% end %>
        </div>
      </div
    </header>
    <%= yield %>
  </body>
</html>